import { Inter } from 'next/font/google'
import './globals.css'
import ResponsiveNavbar from '@/components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'NotifHi - Spheron based notification system',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ResponsiveNavbar />
        {children}
      </body>
    </html>
  )
}
